### ISSUE TITLE
lab lint return code is always zero

### ISSUE THREAD

**Issue by bartlibert** [lighttiger2505/lab#68]
It would be nice to have "lab lint" return an error code if the validate file is not valid.
This would e.g. allow to integrate this into git hooks easily

**Comment by lighttiger2505** [comment]
Thanks for contribution.

Fix complate. b8d4608e4cdd3b7f167c4b0ec3eca7294e3d5e5e

**Comment by mschaaf** [comment]
I verified it is fixed. How about closing this issue?

**Comment by lighttiger2505** [comment]
@mschaaf  Thank you for the reminder. We will close this issue.
