### ISSUE TITLE
Does not work with multiple subgroups

### ISSUE THREAD

**Issue by bartlibert** [lighttiger2505/lab#71]
_Note: some information obfuscated because this is work-releated_

I have a repo set up as follows:

`gitlab.<mydomain>:<group>/<subgroup1>/<subgroup2>/<repo>.git
`

When I try to do any lab command in this repo, I get the result:

`Not found gitlab remote repository`

I noticed that the NewremoteInfo function can only handle one subgroup (https://github.com/lighttiger2505/lab/blob/1a365216e82f70de90e0e329e335c9f88ddb4ace/git/remote.go#L17), so in my case, it will have the following information:
```
Repository: <repo>
SubGroup: <subgroup2>
Group: <subgroup1>
Domain: <group>
```

Hence, it does not work.

**Comment by bartlibert** [comment]
Thanks for the quick fix. I have some trouble building the master at the moment (and no time to look deeper into it), but I'm looking forward to the release with this fix!

**Comment by lighttiger2505** [comment]
@bartlibert Release complete.

https://github.com/lighttiger2505/lab/releases/tag/v0.6.2
