### ISSUE TITLE
Clarify relation to zaquestion/lab

### ISSUE THREAD

**Issue by varac** [lighttiger2505/lab#78]
Having two similar named projects that mostly try to solve the same problem is confusing.
Could you please at least mention zaquestion/lab in the README.md, and why users should use this project instead of the other ? What's the main difference (at first sight I like that this project can handle multiple gitlab instances, while [zaquestion/lab doesn't](https://github.com/zaquestion/lab/issues/151).

Also, did you consider working together on one project instead of two ?

**Comment by varac** [comment]
Oh I see this is mostly a duplicate of #65.
However, it would still be nice to mention the existance of zaquestion/lab in the README.md together with the differences.

And why you don't work together to produce an even more feature complete tool, because both have features that the other doesn't and that's a pity !

**Comment by lighttiger2505** [comment]
Sorry to be late. Thank you for the question.

> Also, did you consider working together on one project instead of two ?

First of all, what you are saying is correct.
Certainly, the problem that both lab commands are trying to achieve is the same.
The concentration of development resources has not a few effects on tool evolution.

Here's why I can not contribute to zaquestion/lab

1. Poor English
1. Philosophy difference

## Poor English

The biggest problem is that I am not good at English. This reply is also mostly powered by Google Translation.
So when adding functionality to smaller things like CLI client, writing your own code is faster than writing ISSUE and PR.

I am trying to solve this problem now.

## Philosophy difference

There is a preference for the CLI client interface. I like the interface of my tool.

## Finally

Someday I may drop the lighttiger2505/lab and contribute to zaquestion/lab.
But now it is impossible.

I want you to allow it by writing README about zaquestion/lab as an interim measure now

**Comment by varac** [comment]
@lighttiger2505 ok, thanks for your detailed answer !

**Comment by lighttiger2505** [comment]
ee6d788006a83c0253e27b2deebd8f2c4396fe35

Added. Closed.
