### ISSUE TITLE
Allow to create merge-requests with the options squash and remove_source_branch

### ISSUE THREAD

**Issue by mschaaf** [lighttiger2505/lab#79]
Hej,
thanks for the nice tool. I would like to request to have the options to set squash and remove_source_branch on a merge request creation.

In the gitlab UI squash is called "Squash commits when merge request is accepted." and remove_source_branch is called "Delete source branch when merge request is accepted.".

**Comment by lighttiger2505** [comment]
Thank's for contribute.

Sorry for being late. Added the your request command options.

**Comment by mschaaf** [comment]
Thanks, it works.
