### ISSUE TITLE
How to uninstall lab properly

### ISSUE THREAD

**Issue by mmngreco** [lighttiger2505/lab#86]
I'm wondering how to uninstall lab properly. There is a guide about this issue?

**Comment by lighttiger2505** [comment]
See [README.md](https://github.com/lighttiger2505/lab#configuration)

Please remove config file.
The config file path is `$HOME/.config/lab/config.yml`.

**Comment by mmngreco** [comment]
Thank you, so removing the configuration file is enough or I should also remove the binary?

**Comment by lighttiger2505** [comment]
If you only want to delete the secret credential of the lab command, deleting the config file is sufficient.

If you want to delete the binary, type `$ which lab` on the command line to delete the displayed file.
This is a general linux/unix procedure.

**Comment by mmngreco** [comment]
thanks for your support!
